language: python

python:
  - "2.7"

install:
  - sudo apt-get install freecad
  - pip install setuptools wheel
  - python setup.py develop

script:
  - python scripts/cad_analyzer.py -m models/sample.STEP

sudo: false

notifications:
  email: false