language: python

python:
  - "2.7"

install:
  - sudo apt-get install freecad
  - pip install -r requirements.txt

script:
  - python scripts/cad_analyzer.py


sudo: false

notification
  - email: false